apiVersion: v1
kind: Template
metadata:
  name: memcached
  annotations:
    description: "Memcached 是一个高性能的分布式内存对象缓存系统，
    用于动态Web应用以减轻数据库负载。它通过在内存中缓存数据和对象来减少读取数据库的次数，
    从而提高动态、数据库驱动网站的速度。Memcached基于一个存储键/值对的hashmap。
    其守护进程（daemon ）是用C写的，但是客户端可以用任何语言来编写，并通过memcached协议与守护进程通信。"
    tags: amq
    iconClass: icon-memcached
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      component: memcached
    name: memcached
  spec:
    type: ClusterIP
    clusterIP: None
    selector:
      component: memcached
    ports:
      - name: memcached
        port: 11211
        protocol: TCP
        targetPort: 11211

- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    labels:
      component: memcached
    name: memcached
  spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
      matchLabels:
        component: memcached
    serviceName: memcached
    podManagementPolicy: Parallel
    template:
      metadata:
        labels:
          component: memcached
      spec:
        containers:
          - name: memcached
            args: ["memcached", "-m", "64"]
            image: memcached:1.5
            ports:
              - containerPort: 11211
                name: memcached
                protocol: TCP
            livenessProbe:
              tcpSocket:
                port: memcached
            readinessProbe:
              tcpSocket:
                port: memcached
            resources:
              limits:
                cpu: "1"
                memory: 96Mi
              requests:
                memory: 64Mi