apiVersion: v1
kind: Template
metadata:
  annotations:
    description: A flexible and scalable container based Selenium Grid with video recording, live preview, basic auth & dashboard.
    iconClass: icon-zalenium
    openshift.io/display-name: Zalenium
    openshift.io/support-url: https://opensource.zalando.com/zalenium/
    tags: pipelines
  name: zalenium
objects:
- apiVersion: authorization.openshift.io/v1
  kind: ClusterRole
  metadata:
    name: zalenium-role
  rules:
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - pods
    verbs:
    - create
    - delete
    - exec
    - get
    - list
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - services
    verbs:
    - create
    - delete
    - get
    - list
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - pods/exec
    verbs:
    - create
    - get

- apiVersion: authorization.openshift.io/v1
  kind: RoleBinding
  metadata:
    name: zalenium-role
  roleRef:
    name: zalenium-role
  subjects:
  - kind: ServiceAccount
    name: cicd
  userNames:
  - system:serviceaccount:cicd:cicd

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: zalenium
      role: hub
    name: zalenium
  spec:
    replicas: 1
    selector:
      app: zalenium
      role: hub
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: zalenium
          role: hub
      spec:
        containers:
        - args:
          - start
          - --desiredContainers
          - "2"
          - --seleniumImageName
          - xhuaustc/selenium:3
          env:
          - name: ZALENIUM_KUBERNETES_CPU_REQUEST
            value: 500m
          - name: ZALENIUM_KUBERNETES_CPU_LIMIT
            value: "1"
          - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
            value: 1Gi
          image: xhuaustc/zalenium:3
          imagePullPolicy: IfNotPresent
          name: zalenium
          ports:
          - containerPort: 4444
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
          - mountPath: /home/seluser/videos
            name: volume-061x0
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        serviceAccount: cicd
        volumes:
        - name: volume-061x0
          persistentVolumeClaim:
            claimName: zalenium-pvc
    triggers:
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: zalenium
    name: zalenium
  spec:
    ports:
    - name: 4444-tcp
      port: 4444
      protocol: TCP
      targetPort: 4444
    - name: 4445-tcp
      port: 4445
      protocol: TCP
      targetPort: 4445
    selector:
      app: zalenium
      role: hub
    type: ClusterIP
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: zalenium-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi

- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: zalenium
    name: zalenium
  spec:
    port:
      targetPort: 4444-tcp
    to:
      kind: Service
      name: zalenium
      weight: 100
    wildcardPolicy: None