---
- name: Generating serviceaccounts for hawkular metrics/cassandra
  template: src=serviceaccount.j2 dest={{mktemp.stdout}}/templates/metrics-{{obj_name}}-sa.yaml
  vars:
    obj_name: "{{item.name}}"
    labels:
      metrics-infra: support
    secrets:
    - hawkular-{{item.secret}}-secrets
  with_items:
  - name: hawkular
    secret: hawkular-metrics-secrets
  - name: cassandra
    secret: hawkular-cassandra-secrets
  changed_when: no

- name: Set serviceaccounts for hawkular metrics/cassandra
  oc_obj:
    name: "{{ item }}"
    kind: serviceaccount
    namespace: "{{ openshift_metrics_project }}"
    files:
    - "{{ mktemp.stdout }}/templates/metrics-{{ item }}-sa.yaml"
    delete_after: true
  with_items:
  - hawkular
  - cassandra
