---
- name: Backup etcd certificates
  command: >
    tar -czvf /etc/etcd/etcd-server-certificate-backup-{{ ansible_date_time.epoch }}.tgz
    {{ etcd_conf_dir }}/ca.crt
    {{ etcd_conf_dir }}/server.crt
    {{ etcd_conf_dir }}/server.key
    {{ etcd_conf_dir }}/peer.crt
    {{ etcd_conf_dir }}/peer.key
  args:
    warn: no
